version: "3.7"

networks:
  app-network:
    name: ${DOCKER_NETWORK}
    driver: bridge

volumes:
  app_db:
    driver: local
  app_redis:
    driver: local

services: 
  app:
    image: sappachok/docker-laravel-admin-pgsql
    build: .
    #container_name: 'laravelapp'
    ports:
      - 9000:9000
      #- 8080:80
      #- 8000:8000
      
    working_dir: /var/www
    volumes:
      - ./app:/var/www      

    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    #container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Bangkok    
    ports:
      - ${NGINX_PORT:-80}":80"
      - ${NGINX_HTTPS_PORT:-443}":443"
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    networks:
      - app-network
   
  postgres:
    build:
      context: ./docker/postgres
      args:
        - POSTGRES_VERSION=13.2-alpine
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'app_db:/var/lib/postgresql/data' 
    ports:
      - ${DB_PORT:-5432}:5432
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  ### redis ############################################
  redis:
    build: docker/redis
    environment:
      - TZ=Asia/Bangkok
  # ports:
  #     - 127.0.0.1:${REDIS_PORT}:6379
    volumes:
      - 'app_redis:/redis/data'
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

#Docker Networks
#networks:
#  app-network:
#    driver: bridge