FROM php:7.3-fpm-buster

#update timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

RUN apt-get update
RUN apt-get install -y --fix-missing \
    apt-utils gnupg \
    # postgresql
    libpq-dev \
    cron

RUN apt-get install -y libzip-dev zlib1g-dev
RUN docker-php-ext-install pdo pdo_pgsql
RUN docker-php-ext-install zip

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

RUN  docker-php-ext-install mbstring


#####################################
# ImageMagick:
#####################################
USER root
ARG INSTALL_IMAGEMAGICK=false
ENV INSTALL_IMAGEMAGICK ${INSTALL_IMAGEMAGICK}
RUN apt-get install -y libmagickwand-dev imagemagick && \
    pecl install imagick && \
    docker-php-ext-enable imagick

#####################################
# Composer:
#####################################
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN usermod -u 1000 www-data
WORKDIR /var/www

EXPOSE 9000